before_install:
- gem install bundler
language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 12
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
  chrome: stable
env:
  global:
  - PGPORT=5433
dist: xenial
script:
- yarn
- bundle exec rails db:reset RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Op+4XN8zwmXXjjG1xb9HcMCugkgwqJ8UUnV1vR6iUlvR4+EA+7GE+Y40B7/tNRLCy9dOKVuPHEyTCeRIprp+Kj7y9exx8Vh0wbbQFW74EkWpoLQIsFMmvMWEE9O1jSNgN0iKHv5xaP4qRGkF1ehJxXCwGNiOc4T1zgwuxEqI835KkyKZ7xxalpGNYiICDUb6WsLAMJUbQyET9gIXsYZcIArR/jiDsOutp5WEntNAVRjs+MB/j8IX4URQNSTVhG37fnCdsIbzsT/T25qSLGIifkCa9OUR2Ffp51cZI6bRupaLoNDOoaU8UfkA0nJYEQz3GbMLB230sMfAUE0ImNlCZSL2kSQnLptrNA6AxqPGcbafGaM2H7xy0em5BM7/mB85Am9q1hE3a/IShQOP0dDTC56KPZ2ZVr498L9mwnxPDfFuIUcMbpNzLeu06fmzRt+3FACWpuq8RophIAsH1TzH+F6b4mOhJprmbmuKLgnQEBDbrqlaBxxvcP8/LIedmB3Wx3cdtfXitzJ9qPzzkVSE2URle9PNnxcV5tSQZ6KESUQFVveDsJ39sLqfebM3TGqKSleAIOVdGGsFAJ34iAs3iMdayJN6uqMstTcdyu75fS7BD1xppXVrpnMECLdmNd6UumROe5gNFfKuiPeU/gDkMbhCBcRAyL9oHDBpQVDO96U=
  app: represent-application
  run: rails db:migrate
